### ISSUE TITLE
Please update to v3.3.0

### ISSUE THREAD

**Issue by rjsmith** [ctjp/meteor-bootstrap-switch#1]
Hi,

Thanks very much for publishing this meteor package.

I would be very grateful if you could bump the package with the latest released BootstrapSwitch version (v3.3.0).  It is supposed to include a fix for a [particularly annoying bug](https://github.com/nostalgiaz/bootstrap-switch/issues/383) I have just wasted a day trying to workaround before I realised it was a known, and recently-fixed issue!

**Comment by ctjp** [comment]
Bumped :)
